{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}-logs
  labels:
    app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}
  annotations:
  {{- range $key, $value := .Values.persistence.logs.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  accessModes:
  - {{ .Values.persistence.logs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
{{- if .Values.persistence.logs.storageClass }}
{{- if (eq "-" .Values.persistence.logs.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.logs.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
